### ISSUE TITLE
Retrive method can not transfer attchment base64 string body correctly

### ISSUE THREAD

**Issue by MessShawn** [developerforce/Force.com-JavaScript-REST-Toolkit#81] opened 2015-11-13 01:57 UTC
I've got an issue to download attachment body in our app.
We use forcetk retrieve method and never got the body data but the uri(something like '/services/data/v33.0/sobjects/Attachment/00P25000000aiNREAY/Body').
Then I use the ajax method of forcetk client directly to call the resource 'services/data/v33.0/sobjects/Attachment/00P25000000aiNREAY/Body' and every time it results to error handling function. it seems that the responseText is right but when I use btoa(unescape(encodeURIComponent(XXX))) to convert the result into base64 string, the converted data   is never matches correct .
Would you give me some advice here?

**Comment by metadaddy-sfdc** [comment] 2015-11-13 03:36
Can you post the code, and the errors you're seeing in the JavaScript Console?

**Comment by MessShawn** [comment] 2015-11-13 04:09
here is the code: 
![2015-11-13 12 03 42](https://cloud.githubusercontent.com/assets/3095801/11138546/9da90c92-89fe-11e5-8fa3-ba07a4fdb995.png)
and logs:
<img width="470" alt="2015-11-13 12 04 25" src="https://cloud.githubusercontent.com/assets/3095801/11138598/47da83b2-89ff-11e5-9c5a-40ebac95f377.png">

it's a cordova app running on ios device

**Comment by metadaddy-sfdc** [comment] 2015-11-13 04:33
The problem is that the query returns binary data, rather than text ([see the docs](https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/dome_sobject_blob_retrieve.htm)). You should be able to use getChatterFile instead of ajax.

**Comment by MessShawn** [comment] 2015-11-13 05:14
@metadaddy-sfdc thanks for you reply
I've change the code like this:
![2015-11-13 13 09 09](https://cloud.githubusercontent.com/assets/3095801/11139262/276622d6-8a08-11e5-8ada-c7da7416725e.png)
and still got nothing : 
<img width="463" alt="2015-11-13 13 12 34" src="https://cloud.githubusercontent.com/assets/3095801/11139271/44664794-8a08-11e5-97d8-7377b0cfa626.png">

am i missed something here?
I'm very sure the attachment is on the server.

**Comment by MessShawn** [comment] 2015-11-13 06:15
@metadaddy-sfdc I've solved the problem, thanks a lot~

**Comment by metadaddy** [comment] 2015-11-13 06:16
What did you need to change?

On Thursday, November 12, 2015, Simon Xiao <notifications@github.com> wrote:

> @metadaddy-sfdc <https://github.com/metadaddy-sfdc> I've solved the
> problem, thanks a lot~
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/developerforce/Force.com-JavaScript-REST-Toolkit/issues/81#issuecomment-156336321>
> .
>


-- 
Cheers,

Pat

**Comment by MessShawn** [comment] 2015-11-13 06:19
@metadaddy-sfdc use the getChatterFile method to download attachment body and convert the response data as array buffer directly.

**Comment by metadaddy-sfdc** [comment] 2015-11-13 19:28
Great! Closing the issue, since it seems like you're all set.

**Closed by metadaddy-sfdc** 2015-11-13 19:28 UTC
