### ISSUE TITLE
createBlob() fails in Firefox

### ISSUE THREAD

**Issue by flamencojones** [developerforce/Force.com-JavaScript-REST-Toolkit#66] opened 2015-05-28 19:30 UTC
When using Chrome or Safari, the Accept header is set to */* (by the browser?), and all is good. 
In Firefox (38.0.1), however, the Accept header is:
    text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8 
and the API return SOAP instead of JSON. Which in turn causes JSON.parse() to fail with 
   JSON.parse: unexpected character at line 1 column 1 of the JSON data

A quick fix was to force the request header in forcetk.js blob():
        request.setRequestHeader('Accept', '*/*');

**Comment by metadaddy-sfdc** [comment] 2015-05-28 19:36
Yes - I just pushed exactly this fix in fcbb8a7 :-)

Duplicate of #65.

**Closed by metadaddy-sfdc** 2015-05-28 19:36 UTC
